blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/skyward-digital/noicons/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: Suggestion
    url: https://github.com/skyward-digital/noicons/discussions/new?category=ideas
    about: 'Suggest any new ideas you have using our discussion forums.'
  - name: Bug Report
    url: https://github.com/skyward-digital/noicons/issues/new
    about: If you think you've found an actual bug, create a bug report.
